### ISSUE TITLE
.out file in the repos directory, 0 results in results file

### ISSUE THREAD

**Issue by mkarajohn** [punk-security/secret-magpie-cli#61]
I tested this running locally, dockerized, on 2 repos from my org (let's call them A and B). Exact command was this:

```
docker run -v /home/mitch/Workspace/magpie-repos/:/repos -v /home/mitch/Documents/magpie/:/app/results punksecurity/secret-magpie filesystem --path /repos --out results/results --out-format csv --extra-context --single-branch
```

Also tried with `--max-branch-count 300` instead of `--single-branch`

## What I expected to happen
I expected the scan to conclude with any findings  from A and B written in `results.csv` located in the mounted `results` directory and a summary screen, after the script concluded, reflecting the `results.csv` file

## What happened
The scan concluded with a `results.csv` which only contained finfings from B and an `A.out` file in the repos directory (`/home/mitch/Workspace/magpie-repos/`) which includes findings from A, but they are nowhere to be seen in the `results.csv` file, which only includes findings from B. 

I did not expect any file to be written in the `/repos` directory, so much more with an `.out` extension. The existence of this file also crashes the whole process if more than the default branch are included in the scan, with the error:

```
Traceback (most recent call last): Total secret detections: 0 |
  File "/app/main.py", line 81, in <module>
    for result_batch in results:
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/app/tasks.py", line 117, in process_repo
    branches = get_branches(
  File "/app/tasks.py", line 35, in get_branches
    r = GitRepo.init(path)
  File "/opt/venv/lib/python3.10/site-packages/git/repo/base.py", line 1154, in init
    return cls(path, odbt=odbt)
  File "/opt/venv/lib/python3.10/site-packages/git/repo/base.py", line 282, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/opt/venv/lib/python3.10/site-packages/git/repo/base.py", line 363, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

OS: Ubuntu 22.04.2 LTS x86_64 
Kernel: 5.19.0-40-generic

Docker Desktop 4.15.0
Docker version 23.0.1

**Comment by SimonGurney** [comment]
Apologies for the slow response on this, we'll try and reproduce!
